### ISSUE TITLE
Nested zip in memory

### ISSUE THREAD

**Issue by ahoarau** [ctabin/libzippp#177]
I would like to read a zip that contains a zip as well:
```
my_archive.zip
      -> my_nested_archive.zip
                   --> my_file.txt
```

I'm looking for the best strategy to avoid having to decompress the nested zip to be able to read inside, in memory.
Let's say I want to just list the files inside the zip.

Seems possible with `libzip`, but I'm unfamiliar with the naming (https://github.com/nih-at/libzip/blob/main/lib/zip_fopen_index_encrypted.c)

**Comment by ctabin** [comment]
Hi @ahoarau,

Actually, you can use [this method](https://github.com/ctabin/libzippp/blob/master/src/libzippp.h#L462) with a custom output function and handle it by chunk. However you'll have to load it entirely in-memory in order to create a new ZipArchive from the buffer... 
For now, I do not see any way to stream the zip content to another one, it seems that libzip doesn't provide a way to create a `zip_source` from a stream.
