### ISSUE TITLE
Error when build with libzippp_static.lib

### ISSUE THREAD

**Issue by SolardiaX** [ctabin/libzippp#25]
Lib was success built with VS2017 (VC++ 14) with a little modify in compile.bat.
I created a new solution with the origin tests.cpp to try build an application without any DLL but failed.

Error are:
LNK2001	unresolved external symbol __imp_remove
LNK2001	unresolved external symbol __imp_zip_close
...

I found a similar issue([#4](https://github.com/ctabin/libzippp/issues/4)) here with different error messages (which error messages of unresolved external symbol have no __imp prefix).

Does I miss something or could you update a simple guild to help build static lib?

**Comment by ctabin** [comment]
Hello,

What are the libraries you were compiling statically ? I has some issues with the static version of `libzip` (most probably because of my old cmake version).
The method you're pointing to seems to come from `libzip` not `libzippp`, hence I would dig about the static compilation of `libzip` (maybe you're just missing a USE flag).

Best,
Cédric

**Comment by SolardiaX** [comment]
Finally done with hardcoded in my solution following the guide at here
http://hostagebrain.blogspot.com/search/label/zlib

@ctabin Maybe you can add this to README? As zlib & libzip static building is a nightmare.
