### ISSUE TITLE
Change enums to lowercase

### ISSUE THREAD

**Issue by p-ranav** [ctabin/libzippp#54]
per the [isocpp/CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum5-dont-use-all_caps-for-enumerators).

> ## Enum.5: Don't use ALL_CAPS for enumerators
> ### Reason
> Avoid clashes with macros.
> 
> ### Example, bad
> ```cpp
>  // webcolors.h (third party header)
> #define RED   0xFF0000
> #define GREEN 0x00FF00
> #define BLUE  0x0000FF
> 
> // productinfo.h
> // The following define product subtypes based on color
> 
> enum class Product_info { RED, PURPLE, BLUE };   // syntax error
> ```
> 
> ### Enforcement
> Flag ALL_CAPS enumerators.

I can imagine `READ_ONLY` and `WRITE` being macros in the embedded world.

**Comment by ctabin** [comment]
Hi @p-ranav,

Seems legit, I did it like this because I come from the Java world :sweat_smile:
Refactoring this will cause some breaking changes :fearful:, so it will require a new major version and unfortunately I just released v3.0 the other day, but I'll consider it for the next update.

Thanks for the report :thumbsup: If you don't mind submitting a PR, you're welcome.
