### ISSUE TITLE
Does readEntry reads an entry completely to memory?

### ISSUE THREAD

**Issue by jfgmmg** [ctabin/libzippp#8]
From reading the comments and the source code, unlike libzipp's `zip_fread`, apparently `ZipArchive::readEntry` reads and entire entry to memory. Is this true? If so, what happens if the entry is a 20GB file?

**Comment by Mezrin** [comment]
Faced the same issue.
Yes, it reads entire entry into the memory.

Also it does not clean memory on object destruction.
So, it you did `void* binaryData = entry.readAsBinary();` you need to clean it `delete[] binaryData;`.
Otherwise you get huge memory leak.
Docs must be updated or source code fixed

**Comment by ctabin** [comment]
Hello,

@jfgmmg  Yes ZipArchive::readEntry read the full entry into memory. Actually, there is no way in the libzip library to handle a seekable data loading, you can only specify the number of bytes you want to read from the start of the stream. Hence, if you have a (very) large file, I'm afraid you're stuck and will have to handle it another way...
I just committed an update to the public API of libzipp, allowing you to also specify the size while reading an entry.

@Mezrin The API doc is already up-to-date and clearly specifies that the data has to be deleted once used.
